/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ribbon_demo.h"
using namespace RIBBON_FILTER;
/* Header for class org_apache_hadoop_hbase_util_RibbonHelper */

#ifndef _Included_org_apache_hadoop_hbase_util_RibbonHelper
#define _Included_org_apache_hadoop_hbase_util_RibbonHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    initRibbonFilter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_initRibbonFilter
        (JNIEnv *, jobject, jint);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    addKey
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_addKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    backSubst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_backSubst
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    filterQuery
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_filterQuery
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
