/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ribbon_demo.h"
#include <deque>

using namespace RIBBON_FILTER;
/* Header for class org_apache_hadoop_hbase_util_RibbonHelper */

#ifndef _Included_org_apache_hadoop_hbase_util_RibbonHelper
#define _Included_org_apache_hadoop_hbase_util_RibbonHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    initRibbonFilter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_initRibbonFilter
        (JNIEnv *, jobject, jint);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    addKey
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_addKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    addRang
 * Signature: ([Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_addRang
        (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    addRangAndInit
 * Signature: (I[Ljava/lang/String;IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_addRangAndInit
        (JNIEnv *, jobject, jint, jobjectArray, jint, jboolean);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    backSubst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_backSubst
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    filterQuery
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_filterQuery
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    printDuration
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_printDuration
        (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    getAddDuration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_getAddDuration
        (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    getBackSubstDuration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_getBackSubstDuration
        (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    getQueryDuration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_getQueryDuration
        (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    getStringToCharsDuration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_getStringToCharsDuration
        (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    getInitDuration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_getInitDuration
        (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    getStringToHash64Duration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_getStringToHash64Duration
        (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_util_RibbonHelper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hbase_util_RibbonHelper_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
